FROM rust:1.74 AS builder

WORKDIR /agent

COPY . .
RUN cargo build --release --bin tat_agent

FROM ubuntu:22.04 AS ship

ENV TZ=Asia/Shanghai

WORKDIR /usr/local/bin

COPY --from=builder /agent/target/release/tat_agent .

ENTRYPOINT ["./tat_agent", "--console-log", "--no-daemon"]

